Store access token in local storage
marszub/savings-planner pull request #42
Opened 2022-05-01 18:49 UTC by elacymerys

2022-05-01 19:02 UTC, MaksymilianK requested changes

2022-05-01 19:02 UTC, MaksymilianK commented on planner-front/src/services/token-storage.js
> +        localStorage.setItem("accessToken", newToken);
I would extract this string literal ("accessToken") to a const.

2022-05-01 19:02 UTC, MaksymilianK commented on planner-front/src/services/token-storage.js
>  }
Please add a newline at the end of the file.

2022-05-02 23:02 UTC, MaksymilianK requested changes

2022-05-03 12:43 UTC, elacymerys commented on planner-front/src/services/user-service.js
> +        localStorage.setItem(USER_NICK, formModel.login);
I forgot to change USER_NICK to USER_LOGIN, but probably it's a good idea to always display nick.

2022-05-03 14:02 UTC, MaksymilianK approved these changes

2022-05-03 17:19 UTC, merged